import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/shared/navBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased mx-5 text-black`}
      >
        <NavBar></NavBar>
        <div className='container mx-auto text-white'>
        {children}
        </div>
      </body>
    </html>
  );
}
